import abc
from abc import ABC, abstractmethod

class OCRBase(ABC, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @abstractmethod
    def extract_text(self, **kwargs) -> str: ...
    def save_txt(self, text: str, output_path: str) -> None: ...
