[project]
name = "pygrpdfocr-workspace"
authors = [
    {name = "ruizgabriel161",email = "ruizgabriel161@outlook.com"}
]
version = "0.1.1"
description = "Biblioteca de ocr para pdf" 
requires-python = ">=3.13.1"
readme = "README.md"
license = "MIT"
dependencies = [
    "rich>=14.2.0",
    "pygrlogging",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
]

# ============================
# uv config
# ============================

[tool.uv]
managed = true # gerenciado pelo uv
package = false # não é um pacote

[tool.uv.workspace]
members = ["packages/*"] #onde está os pacotes

# ============================
# Lista os pacotes
# ============================


[tool.uv.sources]
pygrpdfimage = {workspace = true} 
pygrocrimage = {workspace = true} 

# ============================
# ruff config docs: https://docs.astral.sh/ruff/
# ============================

[tool.ruff]
line-length = 88
target-version = "py314"
fix = true
show-fixes = true
indent-width = 4
exclude = ["venv", ".venv", "env", ".env", "node_modules", "__pycache__"]

[tool.ruff.lint]
select = ['I', 'F', 'E', 'W', 'PL', 'PT']


[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN201", "S101"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"

# ============================
# pyright config
# ============================

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.13"
include = ["packages"]
exclude = [
  "**/venv",
  "**/.venv",
  "**/env",
  "**/.env",
  "**/node_modules",
  "**/__pycache__",
]
venv = ".venv"
venvPath = "."
executionEnvironments = [{ root = "packages" }]
reportMissingTypeStubs = true
stubPath = "stubs"

extraPaths = [               # ← substitui executionEnvironments
  "packages/pygrocrimage/src",
  "packages/pygrpdfimage/src",
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pytest>=9.0.3",
    "ruff>=0.15.11",

]
